### PR TITLE
Tidy docs for initial release

### PR DESCRIPTION
**Pull request by misraved**
Thanks @Mr-Destructive for this amazing new plugin 🎉 !!

This PR includes the following changes:
- `docs/index.md` file now includes the correct org name and also includes the correct path for the social graphics and icons.
- Addresses minor formatting issues in the table docs
- Fixes the correct org name in the Makefile

### CODE REVIEW

**Comment by Mr-Destructive** [comment]
Thanks!  :+1:

**Comment by Mr-Destructive** [comment]
The plugin name `Mr-Destructive/cohereai` can that just be `cohereai`? @misraved

**Comment by misraved** [comment]
@Mr-Destructive the plugin name will be displayed as `cohereai`, however for installation purposes, we have to use the `orgname/pluginname`.

**Comment by Mr-Destructive** [comment]
Ok, got it. So to keep it consistent with other plugins, should I transfer the repository to turbot org?

**Comment by misraved** [comment]
@Mr-Destructive that's not required, we have a lot of plugins on our hub site from other contributors that are maintained in separate orgs. This plugin is now consistent with our plugin standards and looks good to be released to the hub 👍.

**Comment by Mr-Destructive** [comment]
OK, Cool!

**Pull request merged**
